import { Router } from "express";

export const notificationsRouter = Router();

// GET /api/notifications
// Notifications are per-user and generated by the system. A freshly
// onboarded user has none yet, so this returns an empty list until an
// authenticated user + notification pipeline exists.
notificationsRouter.get("/", (_req, res) => {
  res.json([]);
});
